env:
  global:
    - secure: "OHbE6y2cgUHxx8aHZG3NOImyy/0i2T5oNxuSeatG5DLEUEDlj1PdkYINyhP3\nruB8e7XMQgUfq43GnUlRKzmrEnKFwJZo6m4+NIogwTFljB0HfD07beSNL+UY\nws2s3uedtt97op41rj7ZZxIgCrhAjG+BA89dmH3eV8DwWj7eh6Q="
  matrix:
    - FOO=true BAR=False

python: 2.7

matrix:
  include:
    - python: 2.7
      env: FAZ=true BOO=False
      # + STORE_KEY0 or STORE_KEY1, whatever decrypts
    - python: 2.6
      env: FOZ=true BAO=False
      # + STORE_KEY0 or STORE_KEY1, whatever decrypts

# At max one secure envar decrypts, so we get the key iff
# the build was initiated on a whitelisted fork or ""otherwise
script:
    - printenv
