language: ruby
rvm:
  - 1.9.3
branches:
  only:
    - master
    - gh-pages
notifications:
  email: false
  # irc:
  #   channels: "irc.freenode.org#travisstaging"
  #   template: "[STAGING] %{repository} (%{commit}) %{build_url} : %{message}"
  # flowdock: e533e9b0984a1cc7650579ab7aaab158
  # hipchat: "a21b28b2863acbee3ccb17da36a173@Travis CI"
  # campfire:
  #   on_success: 'always'
  #   on_failure: 'always'
  #   rooms:
  #     - secure: "wsimFvFeiaecL+H6f/c4omWkuU/fPnHPZMclWGkZUU6AGNpphuodyPJnFI63\nvGsIlcNcTTVUi0smmQJIVV3jQT9nU/Dr3ULodPD7Wj0NX6kkRFqAGgBJEZ1f\n/NwAlRXxg+Sx3HlGIUitsxILLGJ4lCWVRPPj7Ux63HRaA/MEWSs="
  # webhooks:
  #   urls: http://requestb.in/1guktrt1
  #   on_start: always
  #   on_finish: always

script:
#  - bundle exec rspec spec
  - rake
  - echo "Svens got a lovely bunch of coconuts"

before_script:
  - "echo $FOO"
  - "echo 'Before script'"
  - "sudo service postgresql restart"

after_script:
  - "echo 'After script'"
  - printenv

after_success:
  - "echo 'After success'"

after_failure:
  - "echo 'After failure'"

env:
  global:
    - secure: "XNC/pocPK7h1Ti+ZROAwTtnQpupAVjhMVY4nDMJvYLCaNnLyu37HqgLJcUm4\ns4+WKVz38MNOKnCWSBQyqdmc8YnfIl8Lm91ulAFJGRdTwCF5CEYeOy50TpqL\nhbgJUDDIi7xZq/WfIQKNoMUcXoJnwap37TKQhTr8ojnRnLMsOC4="
