branches:
  only: master
notifications:
  email: false
  irc: 
    channels: "irc.freenode.org#travisstaging"
    template: "(STAGING) %{repository_url} (%{commit}): %{message}"
  webhooks: 
    - http://www.postbin.org/1cig81y
