branches:
  only: master
notifications:
  email: svenfuchs@artweb-design.de
  irc: 
    channels: "irc.freenode.org#travisstaging"
    template: "(STAGING) %{repository_url} (%{commit_short}): %{message}"
  webhooks: 
    - http://www.postbin.org/1cig81y
