env:
  global:
    - secure: "tnEAf34ZvnfNdM+q39+v9o/jNO8pBlT0v1fOzqjPxnCSDf8heZGowoC//N78\nRIg31ghSBujwF6vX0KNmqkp+YIoBbIQ3FV0RAfBvPjMTHb6gEIzNjKkit++O\nbRwY+DugYEsnTI02QzAeF+XffMFdcb0JAzu35LhUTnpGLtmAPL4="
  matrix:
    - FOO=true BAR=False

python: 2.7

matrix:
  include:
    - python: 2.7
      env: FAZ=true BOO=False
      # + STORE_KEY0 or STORE_KEY1, whatever decrypts
    - python: 2.6
      env: FOZ=true BAO=False
      # + STORE_KEY0 or STORE_KEY1, whatever decrypts

# At max one secure envar decrypts, so we get the key iff
# the build was initiated on a whitelisted fork or ""otherwise
script:
    - printenv
