branches:
  only: master
notifications:
  # email: me@svenfuchs.com
  irc:
    channels: "irc.freenode.org#travisstaging"
    template: "[STAGING] %{repository} (%{commit}) %{build_url} : %{message}"
  # webhooks:
  #  urls: http://www.postbin.org/1cig81y
  #   # on_start: always
env:
  - secure: "eh87ToNrBEfMUAtzSUreyE/YxhXf+rEtmJkMSNFfEai9/XdIopbPHoWKLz+h\nfLLejLYTw2m5ifuccPUukdJBbztzaM/i8Pv3FHdWsezH8MUWJTRMYE9Iu1xJ\ng6AgPkof5HarRtpNhWi356IaRbjmrQJHdnx4PXRNjMCm4Fryr00="

