language: ruby
rvm:
  - 1.9.3
before_install:
  - gem install bundler --pre
before_script:
  - 'wget http://phantomjs.googlecode.com/files/phantomjs-1.7.0-linux-i686.tar.bz2'
branches:
  only: master
notifications:
  email: false
  irc:
    channels: "irc.freenode.org#travisstaging"
    template: "[STAGING] %{repository} (%{commit}) %{build_url} : %{message}"
  flowdock: e533e9b0984a1cc7650579ab7aaab158
  hipchat: "a21b28b2863acbee3ccb17da36a173@Travis CI"
  webhooks:
    urls: http://requestb.in/1guktrt1
    on_start: always
    on_finish: always

after_success:
  - "echo 'After success'"

after_success:
  - "echo 'After failure'"

after_test:
  - "echo 'Yupi\!\!\!\!\!'"
  - "echo 'Splendid\!'"
  - printenv

# env:
#   global:
#     - FOO: bar
