branches:
  only: master
before_script: 'wget http://phantomjs.googlecode.com/files/phantomjs-1.7.0-linux-i686.tar.bz2'
notifications:
  email: false
  irc:
    channels: "irc.freenode.org#travisstaging"
    template: "[STAGING] %{repository} (%{commit}) %{build_url} : %{message}"
  flowdock: e533e9b0984a1cc7650579ab7aaab158
  hipchat: "a21b28b2863acbee3ccb17da36a173@Travis CI"
  webhooks:
    urls: http://requestb.in/10wjmvl1
    on_start: always
    on_finish: always

# env:
#   global:
#     - FOO: bar
