language: ruby
rvm:
  - 1.9.3
branches:
  only:
    - master
    - gh-pages
notifications:
  email: false
  # irc:
  #   channels: "irc.freenode.org#travisstaging"
  #   template: "[STAGING] %{repository} (%{commit}) %{build_url} : %{message}"
  flowdock: e533e9b0984a1cc7650579ab7aaab158
  hipchat: "a21b28b2863acbee3ccb17da36a173@Travis CI"
  # campfire:
  #   on_success: 'always'
  #   on_failure: 'always'
  #   rooms:
  #     - secure: "wsimFvFeiaecL+H6f/c4omWkuU/fPnHPZMclWGkZUU6AGNpphuodyPJnFI63\nvGsIlcNcTTVUi0smmQJIVV3jQT9nU/Dr3ULodPD7Wj0NX6kkRFqAGgBJEZ1f\n/NwAlRXxg+Sx3HlGIUitsxILLGJ4lCWVRPPj7Ux63HRaA/MEWSs="
  # webhooks:
  #   urls: http://requestb.in/1guktrt1
  #   on_start: always
  #   on_finish: always

script:
#  - bundle exec rspec spec
  - "git clone https://github.com/travis-repos/test-project-1.git"
  - rake

before_script:
  - "echo $FOO"
  - "echo 'Before script'"
  - "sudo service postgresql restart"

after_script:
  - "echo 'After script'"
  - printenv

after_success:
  - "echo 'After success'"

after_failure:
  - "echo 'After failure'"

env:
  global:
    - secure: "JHG1MTxDt3+a8Pee/qPLSq0n1z4S5TrV4+Zmy3OVMqJY6+45wMu4BB0gru89\nOPWQwe0ifm8IHehP5pUeqQegBAyUm9Iz6iDkL2nxcL0tPQe1rmFB9GrL2mmC\nxeoIgN7m5eJmgzhSJAfIXoHDr79sJx5DQnrc971C/xrA8nZHQoU="
